"use strict";

var data = {
    "g":
    [
    {"front":0, "year":"2022", "title":"Purgatory Area", "desc":"Mouse-only platformer, with twists.", "link":"https://www.newgrounds.com/portal/view/847845"},
    {"front":0, "year":"2022", "title":"QR Tale", "desc":"Storytelling with a QR scanner.", "link":"https://toadietechnika.itch.io/qr-tale"},
    {"front":0, "year":"2022", "title":"Love Nightmare", "desc":"Collect all the hearts, in ups and downs.", "link":"https://www.newgrounds.com/portal/view/832657"},
    {"front":1, "year":"2021", "title":"Underblood", "desc":"Mouse controlling blood flow.", "link":"https://www.newgrounds.com/portal/view/790698"},
    {"front":0, "year":"2021", "title":"News System", "desc":"Mass shooting poops.", "link":"https://www.newgrounds.com/portal/view/781776"},
    {"front":0, "year":"2021", "title":"January One", "desc":"Lost and found story.", "link":"https://www.newgrounds.com/portal/view/779484"},
    {"front":0, "year":"2021", "title":"Password System", "desc":"Pretending social media access.", "link":"https://www.newgrounds.com/portal/view/778623"},
    {"front":0, "year":"2020", "title":"AZ101ESB", "desc":"101 keys to press.", "link":"https://www.newgrounds.com/portal/view/766732"},
    {"front":0, "year":"2020", "title":"Frog Typing Tongue", "desc":"Frog's tongue made of texts.", "link":"https://www.newgrounds.com/portal/view/760187"},
    {"front":1, "year":"2020", "title":"Prism Light", "desc":"Mouse maze with a light.", "link":"https://www.newgrounds.com/portal/view/756495"},
    {"front":1, "year":"2020", "title":"Coordinator", "desc":"Pointing destinations. No bumps.", "link":"https://www.newgrounds.com/portal/view/753993"},
    {"front":0, "year":"2019", "title":"May One", "desc":"&quot;Break Up&quot; Story.", "link":"https://www.newgrounds.com/portal/view/735909"},
    {"front":1, "year":"2019", "title":"Point_Line", "desc":"Connecting points, avoiding colored lines.", "link":"https://www.newgrounds.com/portal/view/732456"},
    {"front":0, "year":"2019", "title":"Home System", "desc":"What is home for you?", "link":"https://www.newgrounds.com/portal/view/725371"},
    {"front":1, "year":"2018", "title":"Ai System", "desc":"Decreasing hearts to advance.", "link":"https://www.newgrounds.com/portal/view/721136"},
    {"front":0, "year":"2018", "title":"Ticket to Stairs", "desc":"Clicking for tickets and one fraud.", "link":"https://www.newgrounds.com/portal/view/718923"},
    {"front":0, "year":"2018", "title":"Keypad Invaders", "desc":"Shooting aliens with a keypad.", "link":"https://www.newgrounds.com/portal/view/716514"},
    {"front":0, "year":"2018", "title":"Capacity System", "desc":"Time then occupy.", "link":"https://www.newgrounds.com/portal/view/715425"},
    {"front":0, "year":"2018", "title":"Don't Let it Get To You", "desc":"Pointing out bad words with a finger.", "link":"https://www.newgrounds.com/portal/view/714411"},
    {"front":0, "year":"2018", "title":"Crowd Nine", "desc":"Filmmaking while a rocket falls.", "link":"https://www.newgrounds.com/portal/view/712764"},
    {"front":1, "year":"2018", "title":"Waiting System", "desc":"Windows updates expanded.", "link":"https://www.newgrounds.com/portal/view/708894"},
    {"front":0, "year":"2018", "title":"Throw Ice Cream", "desc":"Splatting targets, with ice creams.", "link":"https://www.newgrounds.com/portal/view/707759"},
    {"front":0, "year":"2018", "title":"Blind Sword", "desc":"Pause, listen and act.", "link":"https://www.newgrounds.com/portal/view/706054"},
    {"front":1, "year":"2018", "title":"Signal Explorer", "desc":"Make transmission better.", "link":"https://www.coolmathgames.com/0-signal-explorer"},
    {"front":1, "year":"2017", "title":"Pitching", "desc":"Run and dodge with a tempo.", "link":"https://www.newgrounds.com/portal/view/699816"},
    {"front":1, "year":"2017", "title":"Chicken Enters the Door", "desc":"Make the chicken, enter the door.", "link":"https://www.newgrounds.com/portal/view/698205"},
    {"front":0, "year":"2017", "title":"Battery Penetrates", "desc":"Battery fantasy.", "link":"https://www.newgrounds.com/portal/view/697166"},
    {"front":0, "year":"2017", "title":"Sorting 1A", "desc":"Tapping letter blocks chronologically.", "link":"https://www.newgrounds.com/portal/view/689701"},
    {"front":0, "year":"2017", "title":"Laser Unwrapping Gift Boxes", "desc":"Laser shooting gift boxes with a slider.", "link":"https://www.newgrounds.com/portal/view/688159"},
    {"front":1, "year":"2016", "title":"Classic Connect", "desc":"Typing game with mixed characters.", "link":"https://www.newgrounds.com/portal/view/680259"},
    {"front":0, "year":"2016", "title":"Gallery", "desc":"Build figures with matching vertices.", "link":"https://www.newgrounds.com/portal/view/673400"},
    {"front":0, "year":"2016", "title":"Sending Without Ghosts", "desc":"Send pictures, without ghosts.", "link":"https://www.newgrounds.com/portal/view/672664"},
    {"front":0, "year":"2016", "title":"Spheres and Explosive Insomniacs", "desc":"Art inspired by a weird box art.", "link":"https://www.newgrounds.com/portal/view/672461"},
    {"front":0, "year":"2014", "title":"Sight", "desc":"Abstract underwater exploration, in circles.", "link":"https://www.newgrounds.com/portal/view/632703"},
    {"front":0, "year":"2013", "title":"Tree Cleaner Turbo", "desc":"Remove bombs and fires.", "link":"https://www.newgrounds.com/portal/view/629472"},
    {"front":0, "year":"2013", "title":"Anti-Explosive Babies", "desc":"Babies in physics, avoiding explosives.", "link":"https://www.newgrounds.com/portal/view/624040"},
    {"front":0, "year":"2013", "title":"Rotation", "desc":"Weird rotating mechanic yet interesting.", "link":"https://www.newgrounds.com/portal/view/623121"},
    {"front":0, "year":"2013", "title":"Fisher", "desc":"Trying hard sad story. Bad grammar.", "link":"https://www.newgrounds.com/portal/view/618442"},
    {"front":0, "year":"2013", "title":"MinimalFive", "desc":"It has 5 simple minigames.", "link":"https://www.newgrounds.com/portal/view/616448"},
    {"front":1, "year":"2013", "title":"Seed", "desc":"Interpretative game about growing a tree.", "link":"https://www.newgrounds.com/portal/view/615769"}
    ]
    };